version: '3'

services:
  node:
    build: .
    image: node:14
    env_file: .env
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/node
    command: npm run start
    networks:
      - node-network

  postgres:
    image: postgres:13
    ports:
      - '5431:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=leitglxn_test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leitglxn_test
    networks:
      - node-network

networks:
  node-network:
    driver: bridge